-- Engagement Loop 신규 파이프라인 전용 Supabase 스키마
-- 기존 alert/news/sector 테이블과 FK 또는 trigger 의존성을 만들지 않는다.
-- 적용 주체: Supabase SQL Editor의 관리자 역할

BEGIN;

CREATE TABLE IF NOT EXISTS ia_engagement_loops (
    loop_id TEXT PRIMARY KEY,
    schema_version TEXT NOT NULL DEFAULT '1.0',
    week_start_kst DATE NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'planned' CHECK (
        status IN (
            'planned', 'open', 'polling', 'ready_to_score', 'closed',
            'skipped_input', 'cancelled'
        )
    ),
    criteria JSONB NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(criteria) = 'array'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ia_engagement_facts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loop_id TEXT NOT NULL REFERENCES ia_engagement_loops(loop_id) ON DELETE CASCADE,
    phase TEXT NOT NULL CHECK (phase IN ('monday', 'friday', 'calendar')),
    fact_key TEXT NOT NULL,
    value NUMERIC NOT NULL,
    unit TEXT NOT NULL,
    as_of TIMESTAMPTZ NOT NULL,
    source_url TEXT NOT NULL CHECK (source_url LIKE 'https://%'),
    source_name TEXT NOT NULL,
    retrieved_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (loop_id, phase, fact_key)
);

CREATE TABLE IF NOT EXISTS ia_engagement_contents (
    content_id TEXT PRIMARY KEY,
    loop_id TEXT NOT NULL REFERENCES ia_engagement_loops(loop_id) ON DELETE CASCADE,
    slot TEXT NOT NULL CHECK (
        slot IN ('three_numbers', 'scenario_poll', 'scorecard', 'next_week_calendar')
    ),
    revision INTEGER NOT NULL CHECK (revision >= 1),
    body TEXT NOT NULL,
    content_sha256 TEXT NOT NULL CHECK (length(content_sha256) = 64),
    status TEXT NOT NULL DEFAULT 'draft' CHECK (
        status IN ('draft', 'approved', 'published', 'skipped', 'unknown_publication')
    ),
    approved_sha256 TEXT,
    approved_by TEXT,
    approved_at TIMESTAMPTZ,
    approval_expires_at TIMESTAMPTZ,
    x_post_id TEXT,
    x_post_url TEXT,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (loop_id, slot, revision),
    UNIQUE (content_sha256),
    CHECK (approved_sha256 IS NULL OR length(approved_sha256) = 64),
    CHECK (
        status NOT IN ('approved', 'published') OR (
            approved_sha256 = content_sha256
            AND approved_by IS NOT NULL
            AND approved_at IS NOT NULL
            AND approval_expires_at IS NOT NULL
        )
    ),
    CHECK (status <> 'published' OR (x_post_id IS NOT NULL AND published_at IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS ia_engagement_events (
    event_id UUID PRIMARY KEY,
    loop_id TEXT NOT NULL REFERENCES ia_engagement_loops(loop_id) ON DELETE CASCADE,
    content_id TEXT REFERENCES ia_engagement_contents(content_id) ON DELETE SET NULL,
    event_type TEXT NOT NULL,
    from_status TEXT,
    to_status TEXT,
    reason TEXT,
    run_id TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'),
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ia_engagement_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id TEXT NOT NULL REFERENCES ia_engagement_contents(content_id) ON DELETE CASCADE,
    window_hours INTEGER NOT NULL CHECK (window_hours IN (24, 72)),
    measured_at TIMESTAMPTZ NOT NULL,
    impressions BIGINT CHECK (impressions IS NULL OR impressions >= 0),
    likes BIGINT CHECK (likes IS NULL OR likes >= 0),
    replies BIGINT CHECK (replies IS NULL OR replies >= 0),
    reposts BIGINT CHECK (reposts IS NULL OR reposts >= 0),
    bookmarks BIGINT CHECK (bookmarks IS NULL OR bookmarks >= 0),
    meaningful_replies BIGINT CHECK (meaningful_replies IS NULL OR meaningful_replies >= 0),
    raw_metrics JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(raw_metrics) = 'object'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (content_id, window_hours)
);

CREATE TABLE IF NOT EXISTS ia_engagement_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id TEXT NOT NULL REFERENCES ia_engagement_contents(content_id) ON DELETE CASCADE,
    respondent_hash TEXT NOT NULL CHECK (length(respondent_hash) = 64),
    reply_id TEXT NOT NULL,
    selected_option TEXT CHECK (selected_option IN ('A', 'B', 'C')),
    classification TEXT NOT NULL CHECK (
        classification IN ('valid', 'invalid', 'bot', 'author', 'deleted')
    ),
    replied_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (content_id, reply_id)
);

CREATE INDEX IF NOT EXISTS idx_ia_engagement_loops_status
    ON ia_engagement_loops (status, week_start_kst DESC);
CREATE INDEX IF NOT EXISTS idx_ia_engagement_facts_as_of
    ON ia_engagement_facts (loop_id, phase, as_of DESC);
CREATE INDEX IF NOT EXISTS idx_ia_engagement_contents_publication
    ON ia_engagement_contents (published_at DESC) WHERE published_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_ia_engagement_events_loop_time
    ON ia_engagement_events (loop_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_ia_engagement_responses_content
    ON ia_engagement_responses (content_id, replied_at);

-- Monday criteria become immutable as soon as a loop leaves PLANNED.
CREATE OR REPLACE FUNCTION ia_guard_engagement_loop_update()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
    IF (OLD.status <> 'planned' OR NEW.status <> 'planned')
       AND NEW.criteria IS DISTINCT FROM OLD.criteria THEN
        RAISE EXCEPTION 'engagement loop criteria are immutable after PLANNED';
    END IF;
    IF NEW.week_start_kst IS DISTINCT FROM OLD.week_start_kst
       OR NEW.schema_version IS DISTINCT FROM OLD.schema_version THEN
        RAISE EXCEPTION 'engagement loop identity fields are immutable';
    END IF;
    IF NOT (
        (OLD.status = 'planned' AND NEW.status IN ('planned', 'open', 'skipped_input', 'cancelled'))
        OR (OLD.status = 'open' AND NEW.status IN ('open', 'polling', 'ready_to_score', 'cancelled'))
        OR (OLD.status = 'polling' AND NEW.status IN ('polling', 'ready_to_score', 'cancelled'))
        OR (OLD.status = 'ready_to_score' AND NEW.status IN ('ready_to_score', 'closed', 'cancelled'))
        OR (OLD.status IN ('closed', 'skipped_input', 'cancelled') AND NEW.status = OLD.status)
    ) THEN
        RAISE EXCEPTION 'invalid engagement loop status transition: % -> %', OLD.status, NEW.status;
    END IF;
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_ia_guard_engagement_loop_update ON ia_engagement_loops;
CREATE TRIGGER trg_ia_guard_engagement_loop_update
BEFORE UPDATE ON ia_engagement_loops
FOR EACH ROW EXECUTE FUNCTION ia_guard_engagement_loop_update();

-- Audit events are append-only, including for the service role.
CREATE OR REPLACE FUNCTION ia_reject_engagement_event_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
    RAISE EXCEPTION 'engagement events are append-only';
END;
$$;

DROP TRIGGER IF EXISTS trg_ia_reject_engagement_event_update ON ia_engagement_events;
CREATE TRIGGER trg_ia_reject_engagement_event_update
BEFORE UPDATE ON ia_engagement_events
FOR EACH ROW EXECUTE FUNCTION ia_reject_engagement_event_mutation();

-- Client-side access is denied. Only the server-side service role may bypass RLS.
ALTER TABLE ia_engagement_loops ENABLE ROW LEVEL SECURITY;
ALTER TABLE ia_engagement_facts ENABLE ROW LEVEL SECURITY;
ALTER TABLE ia_engagement_contents ENABLE ROW LEVEL SECURITY;
ALTER TABLE ia_engagement_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE ia_engagement_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE ia_engagement_responses ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE ia_engagement_loops FROM anon, authenticated;
REVOKE ALL ON TABLE ia_engagement_facts FROM anon, authenticated;
REVOKE ALL ON TABLE ia_engagement_contents FROM anon, authenticated;
REVOKE ALL ON TABLE ia_engagement_events FROM anon, authenticated;
REVOKE ALL ON TABLE ia_engagement_metrics FROM anon, authenticated;
REVOKE ALL ON TABLE ia_engagement_responses FROM anon, authenticated;

GRANT ALL ON TABLE ia_engagement_loops TO service_role;
GRANT ALL ON TABLE ia_engagement_facts TO service_role;
GRANT ALL ON TABLE ia_engagement_contents TO service_role;
GRANT ALL ON TABLE ia_engagement_events TO service_role;
GRANT ALL ON TABLE ia_engagement_metrics TO service_role;
GRANT ALL ON TABLE ia_engagement_responses TO service_role;
GRANT USAGE, SELECT ON SEQUENCE ia_engagement_facts_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE ia_engagement_metrics_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE ia_engagement_responses_id_seq TO service_role;

COMMIT;

-- Rollback (데이터 삭제가 수반되므로 운영자가 명시적으로 실행):
-- DROP TABLE IF EXISTS ia_engagement_responses;
-- DROP TABLE IF EXISTS ia_engagement_metrics;
-- DROP TABLE IF EXISTS ia_engagement_events;
-- DROP TABLE IF EXISTS ia_engagement_contents;
-- DROP TABLE IF EXISTS ia_engagement_facts;
-- DROP TABLE IF EXISTS ia_engagement_loops;
-- DROP FUNCTION IF EXISTS ia_guard_engagement_loop_update();
-- DROP FUNCTION IF EXISTS ia_reject_engagement_event_mutation();
